### PR TITLE
cleanup and made the project more data oriented

### PR DESCRIPTION
**Pull request by JackGoldsworth**
Cleaned up the main class and added a few packages. I also added a json file called "locations.json" that easily allows for more locations to be added or to change the url if needed.

### CODE REVIEW

**Comment by joel0** [comment]
JDK 10 is EOL ([source](https://www.oracle.com/technetwork/java/javase/downloads/jre10-downloads-4417026.html)).  I could consider downgrading to Java 8 (LTS), but it's going EOL soon, so for now I'll upgrade to JDK 11.  Let me know if you want Java 8 instead of 11.

**Comment by joel0** [comment]
The curly brace style does not match the rest of the project.  Please move them to the same line as the method/if/loop.

I might eventually get around to making these updates myself, but I'd need to figure out how to append changes to your PR.  Thank you for the PR; I appreciate the improvements.

**Comment by JackGoldsworth** [comment]
For the Java 10 issue, I did most of the PR on a computer in the TLA, and they have Java 10 installed on there, so I didn't have much of a choice. I prefer Java 8 of course. There shouldn't be any new features that rely on Java 8+, so that shouldn't be an issue. As for the braces, you could just merge the PR and then commit a reformat.

**Comment by joel0** [comment]
Note: to downgrade to Java 8, `BufferedInputStream.readAllBytes()` would need to be changed.  Instead, I set the project to JDK 11, but limited to language features of Java 10, so it should work unchanged on the TLA.

Thanks you for the contribution!

**Comment by joel0** [comment]
And I did one of the dumbest mistakes: didn't try to compile after making a change.  I reverted the change to `Main.java` in 76fa61249624e829e81f4d5c24e7d01b88dccbcb.

**Pull request merged**
